### ISSUE TITLE
wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by imtinge** [thibaudgg/rb-fsevent#77]
Stack:

>rails 5.1.2
ruby 2.4.1
guard 2.14.1

Error:

```
E, [2017-06-28T22:18:52.571551 #4575] ERROR -- : fsevent: running worker failed: wrong number of arguments (given 2, expected 1):/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/adapter/base.rb:41:in `block (2 levels) in configure'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/rb-fsevent-0.10.0/lib/rb-fsevent/fsevent.rb:75:in `run'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:71:in `_run_worker'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:55:in `_run'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/adapter/base.rb:78:in `block in start'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add' called from: /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:70:in `_run_worker'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:55:in `_run'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/adapter/base.rb:78:in `block in start'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'

E, [2017-06-28T22:18:52.572793 #4575] ERROR -- : fsevent: running worker failed: wrong number of arguments (given 2, expected 1):/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/adapter/base.rb:41:in `block (2 levels) in configure'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/rb-fsevent-0.10.0/lib/rb-fsevent/fsevent.rb:75:in `run'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:71:in `_run_worker'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:81:in `block (2 levels) in _run_workers_in_background'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add' called from: /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:70:in `_run_worker'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:81:in `block (2 levels) in _run_workers_in_background'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'
```

this issue copy from https://github.com/guard/listen/issues/431

**Comment by thibaudgg** [comment]
Could you please give a try to the 0.10.2 release, this issue has been addressed. More info on https://github.com/thibaudgg/rb-fsevent/issues/76.

**Comment by ttilley** [comment]
0.10.0 and 0.10.1 have been yanked from rubygems so that they are no longer installable.

**Comment by imtinge** [comment]
@thibaudgg sorry for this duplicate issue, the 0.10.2 release is work for me. thank you

**Comment by ttilley** [comment]
any time. sorry for the inconvenience.
