### ISSUE TITLE
"`popen': Exec format error" on Windows

### ISSUE THREAD

**Issue by juliend2** [thibaudgg/rb-fsevent#90]
Ruby version:
ruby 2.6.6p146 (2020-03-31 revision 67876) [x64-mingw32]

OS: 
Windows 10 Pro

Code:

```ruby
require "rb-fsevent"
# ...
fsevent = FSEvent.new
fsevent.watch inbox_dir do |directories|
  puts "Detected change in #{directories}"
end
fsevent.run
```

Error:

```
> bundle exec ruby testbed.rb
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rb-fsevent-0.10.4/lib/rb-fsevent/fsevent.rb:140:in `popen': Exec format error - C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rb-fsevent-0.10.4/bin/fsevent_watch (Errno::ENOEXEC)
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rb-fsevent-0.10.4/lib/rb-fsevent/fsevent.rb:140:in `open_pipe'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rb-fsevent-0.10.4/lib/rb-fsevent/fsevent.rb:39:in `run'
        from testbed.rb:57:in `<main>'
```

**Comment by thibaudgg** [comment]
@juliend2 this gem is only supporting macOS FSEvents API, it isn't gonna work on Windows.
